//! Auto-generated library module.
//!
//! This file is auto-generated by nomnom.
//! DO NOT EDIT MANUALLY - changes will be overwritten.
//!
//! High-performance data transformation library with:
//! - Fast, safe data extraction
//! - Automatic code generation from YAML specifications
//! - Python bindings via PyO3

pub mod transform_registry;

// Re-export PyTransformRegistry from nomnom
pub use nomnom::PyTransformRegistry;

// Diesel ORM (database persistence)
pub mod schema;
pub mod models;
pub mod db {
    //! Database connection management and operations
    //!
    //! This module re-exports nomnom's Diesel runtime infrastructure and provides
    //! generated database operations from YAML.

    // Re-export nomnom's generic Diesel infrastructure
    pub use nomnom::diesel_runtime::{
        Database, DatabaseConfig, Pool, PooledConnection,
        GetOrCreate, BulkInsert,
    };

    // Database operations module
    pub mod operations {
        //! Database operations (get_or_create, bulk insert, etc.)
        //!
        //! This module re-exports nomnom's generic operation traits.
        //! Entity-specific implementations are auto-generated in generated_operations.rs.

        // Re-export nomnom's generic traits
        pub use nomnom::diesel_runtime::{GetOrCreate, BulkInsert};

        // GetOrCreate implementations are auto-generated in src/db/generated_operations.rs
        // This is generated by build.rs from entity YAML persistence configs
    }

    pub mod generated_operations;
}

pub mod python {
    //! PyO3 bindings for database operations

    pub mod database {
        //! PyO3 wrapper for Database connection pool
        //!
        //! This module re-exports nomnom's PyDatabase implementation.

        // Re-export nomnom's generic PyDatabase (requires python-bridge feature)
        pub use nomnom::diesel_runtime::PyDatabase;
    }

    pub mod generated_persistence;

    pub use database::PyDatabase;
    pub use generated_persistence::*;
}

// Generated entities (included at compile time)
// This file is generated by build.rs
pub mod generated;
pub use generated::*;
