/// Generate Docker Compose configuration

use crate::codegen::EntityDef;
use super::{BenthosConfig, to_snake_case};
use std::error::Error;

pub fn generate_docker_compose(
    entities: &[&EntityDef],
    config: &BenthosConfig,
) -> Result<String, Box<dyn Error>> {
    let mut services = String::new();

    // Generate a service for each entity
    for entity in entities {
        let entity_snake = to_snake_case(&entity.name);

        services.push_str(&format!(r#"
  benthos-{}:
    image: jeffail/benthos:latest
    container_name: benthos-{}
    volumes:
      - ./pipelines/{}.yaml:/benthos.yaml:ro
    environment:
      NATS_URL: {}
      MYSQL_HOST: {}
      MYSQL_PORT: {}
      MYSQL_DATABASE: {}
      MYSQL_USER: ${{MYSQL_USER:-benthos}}
      MYSQL_PASSWORD: ${{MYSQL_PASSWORD:-benthos}}
      LOG_LEVEL: INFO
    depends_on:
      - nats
      - mysql
    restart: unless-stopped
    networks:
      - benthos-network
"#,
            entity_snake, entity_snake, entity_snake,
            config.nats_url, config.mysql_host, config.mysql_port, config.mysql_database
        ));
    }

    Ok(format!(r#"version: '3.8'

# Auto-generated Docker Compose for Benthos pipelines
# Generated by nomnom

networks:
  benthos-network:
    driver: bridge

volumes:
  nats-data:
  mysql-data:

services:
  nats:
    image: nats:latest
    container_name: nats
    command: ["-js", "-m", "8222"]
    ports:
      - "4222:4222"
      - "8222:8222"
    volumes:
      - nats-data:/data
    networks:
      - benthos-network

  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${{MYSQL_ROOT_PASSWORD:-rootpassword}}
      MYSQL_DATABASE: {}
      MYSQL_USER: ${{MYSQL_USER:-benthos}}
      MYSQL_PASSWORD: ${{MYSQL_PASSWORD:-benthos}}
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./schema:/docker-entrypoint-initdb.d:ro
    networks:
      - benthos-network
{}
"#,
        config.mysql_database,
        services
    ))
}
