/// Generate NATS stream setup scripts

use crate::codegen::EntityDef;
use super::{BenthosConfig, to_snake_case};
use std::error::Error;

/// Generate NATS stream setup scripts (transient + persistent)
pub fn generate_nats_setup_scripts(
    entities: &[EntityDef],
    config: &BenthosConfig,
) -> Result<(String, String), Box<dyn Error>> {
    // Filter transient entities (type: derived)
    let transient_entities: Vec<_> = entities.iter()
        .filter(|e| e.source_type.to_lowercase() == "derived" && !e.is_abstract)
        .collect();

    // Filter persistent entities (type: permanent)
    let persistent_entities: Vec<_> = entities.iter()
        .filter(|e| e.source_type.to_lowercase() == "permanent" && !e.is_abstract)
        .collect();

    let transient_script = generate_setup_script(&transient_entities, "interest", "7d", config)?;
    let persistent_script = generate_setup_script(&persistent_entities, "workqueue", "24h", config)?;

    Ok((transient_script, persistent_script))
}

fn generate_setup_script(
    entities: &[&EntityDef],
    retention: &str,
    max_age: &str,
    config: &BenthosConfig,
) -> Result<String, Box<dyn Error>> {
    let mut script = format!(r#"#!/bin/bash
# Auto-generated NATS stream setup for {} entities
# Generated by nomnom
#
# Retention policy: {}
# Max age: {}

set -e

NATS_URL="${{NATS_URL:-{}}}"

echo "Creating {} entity streams on $NATS_URL with {} retention"

"#,
        retention,
        retention,
        max_age,
        config.nats_url,
        retention,
        retention
    );

    for entity in entities {
        let entity_lower = entity.name.to_lowercase();
        let stream_name = format!("entities_{}", to_snake_case(&entity.name));

        script.push_str(&format!(r#"
echo "Creating stream: {}"
nats stream add {} \
  --subjects "entities.{}" \
  --retention {} \
  --max-age {} \
  --max-msgs 1000000 \
  --max-bytes -1 \
  --storage file \
  --replicas 3 \
  --discard old \
  --dupe-window 2m \
  --server "$NATS_URL" \
  --defaults || echo "  Stream {} already exists"

"#,
            stream_name,
            stream_name,
            entity_lower,
            retention,
            max_age,
            stream_name
        ));
    }

    script.push_str(r#"
echo "All streams created successfully!"
"#);

    Ok(script)
}
