/// Generate nats_client.rs for NATS JetStream connection and publishing

use std::path::Path;
use std::error::Error;
use std::io::Write;

pub fn generate_nats_client_rs(output_dir: &Path) -> Result<(), Box<dyn Error>> {
    let file_path = output_dir.join("src/nats_client.rs");
    let mut file = std::fs::File::create(&file_path)?;

    writeln!(file, "/// NATS JetStream client for message publishing")?;
    writeln!(file, "///")?;
    writeln!(file, "/// Provides connection management and message publishing to NATS JetStream")?;
    writeln!(file)?;
    writeln!(file, "use async_nats::jetstream;")?;
    writeln!(file, "use std::time::Duration;")?;
    writeln!(file, "use crate::message_envelope::MessageEnvelope;")?;
    writeln!(file)?;
    writeln!(file, "#[derive(Clone)]")?;
    writeln!(file, "pub struct NatsConfig {{")?;
    writeln!(file, "    pub url: String,")?;
    writeln!(file, "    pub stream_name: String,")?;
    writeln!(file, "    pub max_age: Duration,")?;
    writeln!(file, "    pub max_bytes: i64,")?;
    writeln!(file, "}}")?;
    writeln!(file)?;
    writeln!(file, "impl Default for NatsConfig {{")?;
    writeln!(file, "    fn default() -> Self {{")?;
    writeln!(file, "        Self {{")?;
    writeln!(file, "            url: std::env::var(\"NATS_URL\")")?;
    writeln!(file, "                .unwrap_or_else(|_| \"nats://localhost:4222\".to_string()),")?;
    writeln!(file, "            stream_name: std::env::var(\"NATS_STREAM\")")?;
    writeln!(file, "                .unwrap_or_else(|_| \"MESSAGES\".to_string()),")?;
    writeln!(file, "            max_age: Duration::from_secs(24 * 60 * 60), // 24 hours")?;
    writeln!(file, "            max_bytes: 1024 * 1024 * 1024, // 1GB")?;
    writeln!(file, "        }}")?;
    writeln!(file, "    }}")?;
    writeln!(file, "}}")?;
    writeln!(file)?;
    writeln!(file, "#[derive(Clone)]")?;
    writeln!(file, "pub struct NatsClient {{")?;
    writeln!(file, "    client: async_nats::Client,")?;
    writeln!(file, "    jetstream: jetstream::Context,")?;
    writeln!(file, "    stream_name: String,")?;
    writeln!(file, "}}")?;
    writeln!(file)?;
    writeln!(file, "impl NatsClient {{")?;
    writeln!(file, "    /// Connect to NATS and initialize JetStream")?;
    writeln!(file, "    pub async fn connect(config: NatsConfig) -> Result<Self, async_nats::Error> {{")?;
    writeln!(file, "        // Connect to NATS")?;
    writeln!(file, "        let client = async_nats::connect(&config.url).await?;")?;
    writeln!(file, "        tracing::info!(\"Connected to NATS at {{}}\", config.url);")?;
    writeln!(file)?;
    writeln!(file, "        // Get JetStream context")?;
    writeln!(file, "        let jetstream = jetstream::new(client.clone());")?;
    writeln!(file)?;
    writeln!(file, "        // Create or get stream")?;
    writeln!(file, "        let _stream = jetstream")?;
    writeln!(file, "            .get_or_create_stream(jetstream::stream::Config {{")?;
    writeln!(file, "                name: config.stream_name.clone(),")?;
    writeln!(file, "                subjects: vec![\"messages.ingest.>\".to_string()],")?;
    writeln!(file, "                max_age: config.max_age,")?;
    writeln!(file, "                max_bytes: config.max_bytes,")?;
    writeln!(file, "                storage: jetstream::stream::StorageType::File,")?;
    writeln!(file, "                num_replicas: 1,")?;
    writeln!(file, "                ..Default::default()")?;
    writeln!(file, "            }})")?;
    writeln!(file, "            .await?;")?;
    writeln!(file)?;
    writeln!(file, "        tracing::info!(\"JetStream stream '{{}}' ready\", config.stream_name);")?;
    writeln!(file)?;
    writeln!(file, "        // Create DLQ stream for failed messages")?;
    writeln!(file, "        let dlq_stream_name = format!(\"{{}}DLQ\", config.stream_name);")?;
    writeln!(file, "        let _dlq_stream = jetstream")?;
    writeln!(file, "            .get_or_create_stream(jetstream::stream::Config {{")?;
    writeln!(file, "                name: dlq_stream_name.clone(),")?;
    writeln!(file, "                subjects: vec![\"messages.dlq.>\".to_string()],")?;
    writeln!(file, "                max_age: Duration::from_secs(7 * 24 * 60 * 60), // 7 days")?;
    writeln!(file, "                max_bytes: 1024 * 1024 * 1024, // 1GB")?;
    writeln!(file, "                storage: jetstream::stream::StorageType::File,")?;
    writeln!(file, "                num_replicas: 1,")?;
    writeln!(file, "                ..Default::default()")?;
    writeln!(file, "            }})")?;
    writeln!(file, "            .await?;")?;
    writeln!(file)?;
    writeln!(file, "        tracing::info!(\"DLQ stream '{{}}' ready\", dlq_stream_name);")?;
    writeln!(file)?;
    writeln!(file, "        Ok(Self {{")?;
    writeln!(file, "            client,")?;
    writeln!(file, "            jetstream,")?;
    writeln!(file, "            stream_name: config.stream_name,")?;
    writeln!(file, "        }})")?;
    writeln!(file, "    }}")?;
    writeln!(file)?;
    writeln!(file, "    /// Publish a message to JetStream")?;
    writeln!(file, "    pub async fn publish_message(")?;
    writeln!(file, "        &self,")?;
    writeln!(file, "        envelope: &MessageEnvelope,")?;
    writeln!(file, "    ) -> Result<(), Box<dyn std::error::Error>> {{")?;
    writeln!(file, "        let subject = format!(\"messages.ingest.{{}}\",")?;
    writeln!(file, "            envelope.entity_type.as_deref().unwrap_or(\"default\"));")?;
    writeln!(file)?;
    writeln!(file, "        let payload = serde_json::to_vec(envelope)?;")?;
    writeln!(file)?;
    writeln!(file, "        // Publish with JetStream (durable, acknowledged)")?;
    writeln!(file, "        let ack = self.jetstream")?;
    writeln!(file, "            .publish(subject.clone(), payload.into())")?;
    writeln!(file, "            .await?;")?;
    writeln!(file)?;
    writeln!(file, "        // Wait for acknowledgment")?;
    writeln!(file, "        ack.await?;")?;
    writeln!(file)?;
    writeln!(file, "        tracing::debug!(")?;
    writeln!(file, "            \"Published message {{}} to JetStream subject {{}}\",")?;
    writeln!(file, "            envelope.message_id,")?;
    writeln!(file, "            subject")?;
    writeln!(file, "        );")?;
    writeln!(file)?;
    writeln!(file, "        Ok(())")?;
    writeln!(file, "    }}")?;
    writeln!(file)?;
    writeln!(file, "    /// Get JetStream context for advanced operations")?;
    writeln!(file, "    pub fn jetstream(&self) -> &jetstream::Context {{")?;
    writeln!(file, "        &self.jetstream")?;
    writeln!(file, "    }}")?;
    writeln!(file, "}}")?;

    Ok(())
}
