//! Database operations (get_or_create, bulk insert, etc.)
//!
//! This module defines generic traits for common database operations.
//! Entity-specific implementations are auto-generated by the codegen module.

use diesel::prelude::*;
use diesel::result::Error as DieselError;

/// Trait for entities that support get_or_create pattern
///
/// This trait provides idempotent entity creation - either returns existing
/// entity if unicity match found, or inserts new entity.
///
/// # Example
///
/// ```ignore
/// use nomnom::diesel_runtime::GetOrCreate;
///
/// let user = User {
///     email: "alice@example.com".to_string(),
///     name: "Alice".to_string(),
/// };
///
/// // Will insert if no user with this email exists, otherwise return existing
/// let saved_user = User::get_or_create(&mut conn, &user)?;
/// ```
pub trait GetOrCreate: Sized {
    /// Get existing entity or create new one
    ///
    /// # Arguments
    /// * `conn` - Database connection
    /// * `instance` - Entity instance to insert (if not exists)
    ///
    /// # Returns
    /// The entity (either existing or newly created)
    fn get_or_create(
        conn: &mut MysqlConnection,
        instance: &Self,
    ) -> Result<Self, DieselError>;

    /// Return list of field names used for unicity check
    ///
    /// These fields determine whether an entity already exists in the database.
    /// For example, a User entity might use ["email"] to prevent duplicate accounts.
    fn unicity_fields() -> Vec<&'static str>;
}

/// Trait for bulk insert operations
///
/// Provides efficient batch insertion of multiple entities.
///
/// # Example
///
/// ```ignore
/// use nomnom::diesel_runtime::BulkInsert;
///
/// let users = vec![
///     User { email: "alice@example.com".to_string(), name: "Alice".to_string() },
///     User { email: "bob@example.com".to_string(), name: "Bob".to_string() },
/// ];
///
/// let inserted_count = User::bulk_insert(&mut conn, &users)?;
/// println!("Inserted {} users", inserted_count);
/// ```
pub trait BulkInsert: Sized {
    /// Insert multiple entities in batches
    ///
    /// # Arguments
    /// * `conn` - Database connection
    /// * `instances` - Slice of entities to insert
    ///
    /// # Returns
    /// Number of entities inserted
    fn bulk_insert(
        conn: &mut MysqlConnection,
        instances: &[Self],
    ) -> Result<usize, DieselError>;
}
